name: text2nerf
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - boltons=23.0.0=py310h06a4308_0
  - brotli-python=1.0.9=py310h6a678d5_7
  - brotlipy=0.7.0=py310h7f8727e_1002
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2023.08.22=h06a4308_0
  - certifi=2023.11.17=py310h06a4308_0
  - cffi=1.16.0=py310h5eee18b_0
  - conda=23.3.1=py310h06a4308_0
  - conda-content-trust=0.1.3=py310h06a4308_0
  - conda-package-handling=2.2.0=py310h06a4308_0
  - conda-package-streaming=0.9.0=py310h06a4308_0
  - idna=3.4=py310h06a4308_0
  - joblib=1.2.0=py310h06a4308_0
  - jsonpatch=1.32=pyhd3eb1b0_0
  - jsonpointer=2.1=pyhd3eb1b0_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - mkl_fft=1.3.8=py310h5eee18b_0
  - mkl_random=1.2.4=py310hdb19cb5_0
  - ncurses=6.4=h6a678d5_0
  - numpy-base=1.26.2=py310hb5e798b_0
  - openssl=3.0.12=h7f8727e_0
  - pip=23.0.1=py310h06a4308_0
  - pluggy=1.0.0=py310h06a4308_1
  - pycosat=0.6.6=py310h5eee18b_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=23.2.0=py310h06a4308_0
  - pysocks=1.7.1=py310h06a4308_0
  - python=3.10.13=h955ad1f_0
  - readline=8.2=h5eee18b_0
  - requests=2.28.1=py310h06a4308_1
  - ruamel.yaml=0.17.21=py310h5eee18b_0
  - ruamel.yaml.clib=0.2.6=py310h5eee18b_1
  - scikit-learn=1.3.0=py310h1128e8f_0
  - setuptools=65.6.3=py310h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - toolz=0.12.0=py310h06a4308_0
  - tzdata=2023c=h04d1e81_0
  - wheel=0.38.4=py310h06a4308_0
  - xz=5.4.2=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - zstandard=0.19.0=py310h5eee18b_0
  - pip:
      - absl-py==1.2.0
      - accelerate==0.15.0
      - aiohttp==3.8.3
      - aiosignal==1.2.0
      - antlr4-python3-runtime==4.9.3
      - anyio==3.6.1
      - asttokens==2.1.0
      - async-timeout==4.0.2
      - attrs==22.1.0
      - backcall==0.2.0
      - bcrypt==4.0.1
      - beautifulsoup4==4.11.1
      - braceexpand==0.1.7
      - cachetools==5.2.0
      - charset-normalizer==2.1.1
      - click==8.1.3
      - clip-anytorch==2.5.0
      - coca-pytorch==0.0.6
      - coloredlogs==15.0.1
      - configargparse==1.5.3
      - contourpy==1.0.5
      - cryptography==38.0.1
      - cudnnenv==0.8.0
      - cycler==0.11.0
      - decorator==5.1.1
      - diffusers==0.11.1
      - easydict==1.10
      - einops==0.5.0
      - einops-exts==0.0.3
      - embedding-reader==1.5.0
      - executing==1.2.0
      - fastapi==0.85.0
      - ffmpy==0.3.0
      - filelock==3.8.0
      - flatbuffers==22.9.24
      - fonttools==4.37.4
      - frozenlist==1.3.1
      - fsspec==2022.8.2
      - ftfy==6.1.1
      - future==0.18.2
      - gdown==4.5.1
      - google-auth==2.12.0
      - google-auth-oauthlib==0.4.6
      - gradio==3.4.1
      - grpcio==1.49.1
      - h11==0.12.0
      - httpcore==0.15.0
      - httpx==0.23.0
      - huggingface-hub==0.10.1
      - humanfriendly==10.0
      - imageio==2.22.0
      - imageio-ffmpeg==0.4.7
      - importlib-metadata==5.0.0
      - intel-openmp==2022.2.1
      - invisible-watermark==0.1.5
      - ipython==8.6.0
      - jedi==0.18.1
      - jinja2==3.1.2
      - kiwisolver==1.4.4
      - kornia==0.6.7
      - lightning-utilities==0.9.0
      - linkify-it-py==1.0.3
      - lpips==0.1.4
      - markdown==3.4.1
      - markdown-it-py==2.1.0
      - markupsafe==2.1.1
      - matplotlib==3.6.1
      - matplotlib-inline==0.1.6
      - mdit-py-plugins==0.3.1
      - mdurl==0.1.2
      - mediapy==1.1.2
      - mkl==2022.2.1
      - mkl-service==2.4.0
      - mpmath==1.2.1
      - multidict==6.0.2
      - networkx==2.8.7
      - ninja==1.11.1
      - numpy==1.23.3
      - oauthlib==3.2.1
      - omegaconf==2.2.3
      - onnx==1.12.0
      - onnxruntime==1.12.1
      - opencv-python==4.6.0.66
      - orjson==3.8.0
      - packaging==23.2
      - pandas==1.5.0
      - paramiko==2.11.0
      - parso==0.8.3
      - patsy==0.5.3
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - pillow==9.2.0
      - plyfile==0.7.4
      - prompt-toolkit==3.0.32
      - protobuf==3.19.6
      - psutil==5.9.4
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pyarrow==7.0.0
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - pycryptodome==3.15.0
      - pydantic==1.10.2
      - pydeprecate==0.3.2
      - pydub==0.25.1
      - pygments==2.13.0
      - pynacl==1.5.0
      - pyparsing==3.0.9
      - pyspng==0.1.1
      - python-dateutil==2.8.2
      - python-multipart==0.0.5
      - pytorch-lightning==1.7.7
      - pytz==2022.4
      - pywavelets==1.4.1
      - pyyaml==6.0
      - regex==2022.9.13
      - requests-oauthlib==1.3.1
      - resize-right==0.0.2
      - rfc3986==1.5.0
      - rotary-embedding-torch==0.1.5
      - rsa==4.9
      - scikit-image==0.19.3
      - scipy==1.11.3
      - sniffio==1.3.0
      - soupsieve==2.3.2.post1
      - stack-data==0.6.0
      - starlette==0.20.4
      - statsmodels==0.14.0
      - sympy==1.11.1
      - tbb==2021.7.1
      - tensorboard==2.10.1
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - threadpoolctl==3.1.0
      - tifffile==2022.8.12
      - timm==0.6.11
      - tokenizers==0.13.1
      - torch==1.13.1+cu116
      - torchaudio==0.13.1+cu116
      - torchmetrics==1.2.0
      - torchvision==0.14.1+cu116
      - tqdm==4.66.1
      - traitlets==5.5.0
      - transformers==4.25.1
      - trimesh==3.16.0
      - typing-extensions==4.3.0
      - uc-micro-py==1.0.1
      - urllib3==1.26.12
      - uvicorn==0.18.3
      - vector-quantize-pytorch==0.10.6
      - wcwidth==0.2.5
      - webdataset==0.2.30
      - websockets==10.3
      - werkzeug==2.2.2
      - x-clip==0.11.0
      - yarl==1.8.1
      - zipp==3.8.1
prefix: /root/miniconda3
